name: flutter_mentorship
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  # Bloc for state management
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  dio: ^5.4.3+1
  # Value equality
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  # For splash screen
  flutter_native_splash: ^2.4.0
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.0
  # A simple cli to manage Flutter SDK versions per project.
  fvm: ^3.0.14
  # Service locator
  get_it: ^7.7.0
  # Checks for internet
  internet_connection_checker: ^1.0.0+1
  # For generate mock classes
  mockito: ^5.4.4
  # Local cache
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.2.3

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
